### ISSUE TITLE
Input events ignored (one out of two)

### ISSUE THREAD

**Issue by romgrk** [rhysd/neovim-component#19]
Introduced by aa7c335ce9aa64e09cc2fd31f90b0f8b2ad86c79 

One out of two input event is ignored

Steps: 
- press `j`
- press `j`

![screenshot from 2016-02-20 05-03-02](https://cloud.githubusercontent.com/assets/1423607/13195988/7f7e5a36-d78f-11e5-8f48-0889df3f6b16.png)

**Comment by rhysd** [comment]
Thanks, I noticed the same.
It seems that `textInput` is different from what I supposed.
