### ISSUE TITLE
Nvim process crash maybe?(or electron?)

### ISSUE THREAD

**Issue by romgrk** [rhysd/neovim-component#23]
Hello,
I'll update the title with something more meaningful as soon as I find out what's going wrong, but I was wondering if I could have your input on a particular issue.
When I try to open certain files in the component, I get a "Inspected target disconnected" popup in DevTools (see image below), and the whole electron window becomes unresponsive.
Do you have any idea where this could come from? I'm not sure where to start debuging. (I'm not sure either that this is a neovim-component issue.)

(The window right after executing `:e sass/main.scss`)
![screenshot from 2016-02-25 03-37-49](https://cloud.githubusercontent.com/assets/1423607/13314309/80714908-db72-11e5-981a-74cfcb4d0162.png)

**Comment by rhysd** [comment]
The 'Inspected target disconnected' message is generally shown when the render process ends before closing DevTools window.  (One DevTools corresponds to one render process (BrowserWindow or webview).

**Comment by rhysd** [comment]
If render process is broken because of Electron bug, some error message may be shown in console.

**Comment by romgrk** [comment]
Definitely not neovim-component, reproduced with electron & other processes.

**Comment by rhysd** [comment]
Thank you for investigation :smile:
