### ISSUE TITLE
No bower.json present

### ISSUE THREAD

**Issue by haifengkao** [rhysd/neovim-component#30]
When I execute `npm start`, the terminal shows
![2016-07-29 1 54 11](https://cloud.githubusercontent.com/assets/4080524/17223490/60213816-552f-11e6-86ba-02a5b14c3bc3.jpg)

It seems that the `bower install` in package.json is not necessary

**Comment by rhysd** [comment]
I don't know why... It actually exist.

https://github.com/rhysd/neovim-component/blob/master/bower.json

**Comment by haifengkao** [comment]
I know why.  It is ignored.

![2016-07-29 4 27 39](https://cloud.githubusercontent.com/assets/4080524/17242377/6aa41ffe-55a9-11e6-980b-effb260c9b11.jpg)

**Comment by rhysd** [comment]
Are you using npm package for development?

npm package is made for production, not for development.  Please clone this repository instead for development.

**Comment by rhysd** [comment]
ah, excluding bower_components may be wrong.  I'll investigate.

**Comment by rhysd** [comment]
I checked.  Actually not a problem.  bower packages are used for development only for this repo.  So prodution (npm package) does not need it.

**Comment by haifengkao** [comment]
I get your point. I indeed use it for development.
But it really troubles me if `bower.json` doesn't present at  `nyaovim/node_modules/neovim-component`. I need to check both `nyaovim` and `neovim-component` to find the location of a possible bug.

**Comment by rhysd** [comment]
I see.  I'll add nower.json to npm package.  Sorry for inconvenience.
