### ISSUE TITLE
How to create a self contained minimal app?

### ISSUE THREAD

**Issue by cancandan** [rhysd/neovim-component#36]
How can one package all dependencies like nvim, electron and have a single executable app?

**Comment by rhysd** [comment]
1. Create new electron app repository
2.  npm install neovim-component
3. Write minimal app referring `example/minimal`
4. Package the app.  Document: https://github.com/electron/electron/blob/master/docs/tutorial/application-packaging.md

electron-packager or electron-builder is greatly helpful for 4.

**Comment by cancandan** [comment]
Thanks but one also needs to include nvim executable to the electron package i think

**Comment by rhysd** [comment]
Please add `nvim` to somewhere in your repository and set an absolute path to the `nvim` at `nvim-cmd` property in `<neovim-editor>` component.

https://github.com/rhysd/neovim-component#neovim-editor-properties

**Comment by cancandan** [comment]
Excellent thank you
