### ISSUE TITLE
Meta/Alt chords input shifted variant to neovim

### ISSUE THREAD

**Issue by romgrk** [rhysd/neovim-component#6]
Steps:
- `electron example/minimal` or `electron example/markdown`
- press `alt-char` where `char` is any letter, e.g. Alt + j
- console.log: `Input to neovim: <A-J>` where we should instead have `<A-j>`

**Comment by rhysd** [comment]
Hi, thank you for the report.

But it is expected behavior.  Neovim/Vim ignores letter cases in input.  So `<A-J>` is equivalent to `<A-j>`.
Please try below:

```vim
" Set from command line
:nnoremap <C-L> :echo 'blah, blah, blah'<CR>

" Then enter Ctrl + l (not shifted).  I think 'blah, blah, blah' is input.
```

**Comment by rhysd** [comment]
Ah, sorry, `<C-` has different behavior from `<A-`.  I got it.

**Comment by rhysd** [comment]
I usually uses Vim so I know that Neovim can handle Alt + Shift.

**Comment by rhysd** [comment]
I fixed.  If you find this bug is still there, please reopen this issue.

**Comment by romgrk** [comment]
Yes, this one should still be open.

**Comment by romgrk** [comment]
But I cannot seem to reopen this issue, the button is not appearing.

Anyway, here is the report:
- neovim-component still firing `<A-J>`, while it should send `<A-j>`
![screenshot from 2015-12-15 05-35-04](https://cloud.githubusercontent.com/assets/1423607/11808314/b64ae2cc-a2ed-11e5-8ca3-17662cb537c2.png)

**Comment by rhysd** [comment]
Hmm... OK, I'll check it later again.

`KeyEvent.keyCode` is too complecated (but Chrome doesn't implement `KeyEvent.key` yet...).
Thank you for the pointer to handling key events.

**Comment by rhysd** [comment]
@romgrk 

I tried again and it seems to work well.  (I used `<A-e>` instead of `<A-j>` because I already assign other OS feature to `<A-j>`.
Could you try again after pulling master branch and building again?

![2015-12-16 2 09 50](https://cloud.githubusercontent.com/assets/823277/11817886/5fbdec3a-a39a-11e5-842b-671d4f44347b.png)

**Comment by romgrk** [comment]
All good doctor.

**Comment by rhysd** [comment]
OK, thanks.
